### PR TITLE
Support WordPress 4 login cookie.

### PR DESCRIPTION
**Pull request by kayue**

### CODE REVIEW

**Comment by Louis94** [comment]
@kayue what exactly is left to do? I would like to help if possible :)

**Comment by kayue** [comment]
@Louis94 Thanks for the offer. The `SessionTokenManager` class in this branch need to be complete. It is being used by `WordpressCookieService` class.

I don't have time to dig into WordPress 4's source code, it would be great if you can help complete it. Feel free to fork this branch. Thanks.

**Comment by kayue** [comment]
Reopened in https://github.com/kayue/KayueWordpressBundle/pull/63

**Comment by Louis94** [comment]
@kayue Just saw your answer! I'll see what I can do :)

**Pull request closed without merging**
